# Generated by Django 5.2.8 on 2025-11-23 11:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('url', models.TextField()),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('posted_date', models.DateTimeField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('resume_text', models.TextField(blank=True, null=True)),
                ('skills', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
